Adds more arguments to trigger a double tap
puzzle/lightning-beer-tap pull request #1
Opened 2019-07-29 14:15 UTC by phil-pona

2019-07-30 06:47 UTC, guggero requested changes
Very nice, thanks!
Just two small things that I found.

2019-07-30 06:47 UTC, guggero commented on gpio_handler/gpio_handler.py
> +        draw_beer(r_ch2,t_left_tap)
Shouldn't this be `draw_beer(r_ch1, t_left_tap)`?

2019-07-30 06:47 UTC, guggero commented on gpio_handler/gpio_handler.py
> +        draw_beer(r_ch2,t_right_tap)
nit: space after comma

2019-07-30 07:26 UTC, merged

2019-07-31 08:42 UTC, id101010 reviewed
Looks good :)